Problem Statement 1:

Write a function so that the columns of the output matrix are powers of the input vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, 
the i-th output column is the input vector raised element-wise to the power of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.

    Input  -  [1, 2, 3]

    Output - [[1,1,1],

              [1,2,4],
          
              [1,3,9]]

In [17]:
import numpy as np
def ATV_matrix(n,lst,order):
    x=np.zeros(((n,n)),dtype=np.int64)
    if order=='TRUE':
        for j in range(0,n):
            for i in range (0,n):
                x[i][j]=((x[i][j]+int(lst[i]))**j)
    elif order=='FALSE':
        for i in range (0,n):
            for j in range(0,n):
                x[i][j]=((x[i][j]+int(lst[i]))**(n-j-1))
    return (x)
            
print("Enter the no of inputs: ")
n=int(input())
lst=[]
print("Enter the Values: ")
for i in range(n):
    lst.append(input())
arr=np.array(lst)
print("Output in Ascending Order (TYPE 'TRUE' ELSE 'FALSE') : ")
order=str(input())
out=ATV_matrix(n,lst,order)
print("Output Matrix formed is : \n",out)

Enter the no of inputs: 
3
Enter the Values: 
10
20
30
Output in Ascending Order (TYPE 'TRUE' ELSE 'FALSE') : 
FALSE
Output Matrix formed is : 
 [[100  10   1]
 [400  20   1]
 [900  30   1]]


Problem Statement 2:

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [26]:
def Mov_avg(lst,n):
    l=len(lst)
    r=l-n+1
    lst1=[]
    for j in range(0,r):
        cal=0
        for k in range(0,n):
            if k==n-1:
                cal=((cal+lst[j+k])/n)
            else:
                 cal=(cal+lst[j+k])
        lst1.append(round(cal,2))
    return lst1
lst = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n = 3
movavg=Mov_avg(lst,n)
print("Moving average value list: ", movavg)
print("Length of the Moving Avg list (l-n+1): ", len(movavg))

Moving average value list:  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
Length of the Moving Avg list (l-n+1):  11
